### ISSUE TITLE
Can it work on Managed/Offline?

### ISSUE THREAD

**Issue by boomsta** [LucasHocker/DynatraceDashboardPowerups#10]
Hi,
What changes need be done to the code in order to get the extension to work offline?

In background.js:
I've changed the urlMatches   to match my environment.   

But still couldn't get it to work (icon hasn't powered up).  Can it be done?

10x,
Daniel

**Comment by LucasHocker** [comment]
Hmm... nothing should be needed to make it work in a Managed Offline scenario. Please reach out to me over email (Lucas dot Hocker at Dynatrace) and we'll set up a time to walk through it together.

**Comment by boomsta** [comment]
My bad-
We had an old chrome version (65~).
After installing 87 everything worked fine.

Thanks !
Daniel
