### ISSUE TITLE
Heatmap calculation error

### ISSUE THREAD

**Issue by TechShady** [LucasHocker/DynatraceDashboardPowerups#12]
The calculation of the heatmap value considers null values as zero. So if a user action executes once in a 24 hour slice, assuming for this example that I have 24 data points, the apdex will be the sum of all values divided by 24. So if my user action has a perfect apdex of 1 and only executed once, then the heatmap will show the apdex as 1/24. Null values need to be excluded so the math is 1/1.

![image](https://user-images.githubusercontent.com/21313331/101080490-da4fad80-3576-11eb-9774-3af020d2518d.png)

**Comment by LucasHocker** [comment]
Bugfix added in 1.36
