### ISSUE TITLE
Heatmap Enhancement Request

### ISSUE THREAD

**Issue by m-probus** [LucasHocker/DynatraceDashboardPowerups#13]
It would be nice to be able to do smaller interval in the Heatmap, such as 5 minutes as we currently have in NAM

**Comment by LucasHocker** [comment]
This one seems a bit harder than expected. Need to change how I'm configuring the xAxis. I'll need to keep noodling this one.

**Comment by LucasHocker** [comment]
Added into version 1.38. You'll set your bucket size with the `ms` parameter and `fmt` to change the date format on the xAxis.
