### ISSUE TITLE
Allow for a fixed color for icons

### ISSUE THREAD

**Issue by TechShady** [LucasHocker/DynatraceDashboardPowerups#18]
Currently, icons are linked to a SV tile and changes color based on thresholds. Allow for a fixed color override. Use case is for icons like a help icon that you want as a fixed color and not based on a SV tile and thresholds. Or an icon that links to another dashboard.

**Comment by TechShady** [comment]
You would need to make the Link and Base options optional. 
Currently I have:
!PU(svg):icon=help-bubble;link=lnk4;base=low;warn=0;crit=3;url=#dashboard;id=0ac9409a-3e01-456b-b2ff-1e401695dbd5
Maybe allow this:
!PU(svg):icon=help-bubble;color=blue;url=#dashboard;id=0ac9409a-3e01-456b-b2ff-1e401695dbd5

**Comment by LucasHocker** [comment]
Released in 1.36
