### ISSUE TITLE
User Experience Forecast Linear Weighted Analysis Issue

### ISSUE THREAD

**Issue by HowardAtNC-DHHS** [LucasHocker/DynatraceDashboardPowerups#20]
The numbers do not agree with the graphs.

![2020_12_23_08_39_37_UserExperienceForecast](https://user-images.githubusercontent.com/76524464/103001892-de2e7a00-44fb-11eb-8dc4-5a4e2fc5d68c.jpg)

**Comment by TechShady** [comment]
I believe this has to do with the tile height and plotting of the data points. I did a few tests in my demo environment and created the graphs 30x7 and the single value tiles 8x7. The graphs scale much better with those settings. Can you edit your dashboard and try these settings? The only downside, depending on your screen zoom, you might need to scroll down to see the later weeks. My screen zoom is set to 67% and it shows most of the rows...
![image](https://user-images.githubusercontent.com/21313331/103012335-71ba7780-4509-11eb-86c1-588e25f55af4.png)

Let me know if resizing the tiles helps.

**Comment by HowardAtNC-DHHS** [comment]
I'm afraid you're missing my point. My Satisfied User Counts should be greater than my Tolerated User Counts.

**Comment by TechShady** [comment]
I see the issue now. I'll push a fix in a few minutes. Thanks for catching this...

**Comment by TechShady** [comment]
Fixed. Relaunch the Configurator and try deploying again. Let me know if the counts are accurate...

**Comment by HowardAtNC-DHHS** [comment]
That did the trick. Thanks.
