### ISSUE TITLE
applications duplicated in App Heatmap

### ISSUE THREAD

**Issue by JACONDE** [LucasHocker/DynatraceDashboardPowerups#22]
When creating the app Heatmap, the stacked bar chart is shown properly the list of apps, but when the plugin does its magic, application list is getting duplicated.

**Comment by JACONDE** [comment]
![image](https://user-images.githubusercontent.com/11209831/103553499-d08ad400-4ead-11eb-9216-399b33dd08a8.png)
Here is attached how apps are shown in the heatmap

**Comment by JACONDE** [comment]
and, here is the list of apps in the chart
![image](https://user-images.githubusercontent.com/11209831/103553636-04fe9000-4eae-11eb-82d4-130fc2caa255.png)

**Comment by LucasHocker** [comment]
This is a known issue when you duplicate colors in the original chart.
![Screen Shot 2021-01-04 at 10 22 50 AM](https://user-images.githubusercontent.com/34926264/103556468-7111d180-4e77-11eb-8f39-fb8c7fe9cb77.png)
![Screen Shot 2021-01-04 at 10 25 35 AM](https://user-images.githubusercontent.com/34926264/103556490-7707b280-4e77-11eb-89bb-df44ecdd6b7a.png)

**Comment by JACONDE** [comment]
YOU ARE COMPLETELY RIGHT !!! Just changed the colors and it works nicely. Thanks Lukas
