### ISSUE TITLE
wrong applications names in Heatmaps

### ISSUE THREAD

**Issue by JACONDE** [LucasHocker/DynatraceDashboardPowerups#23]
![image](https://user-images.githubusercontent.com/11209831/103557716-e7342980-4eb3-11eb-8235-e9e9490cf5f2.png)
Do you know the reason for getting weird app names instead of the ones configured in the applications heatmaps?
Thanks,

**Comment by LucasHocker** [comment]
Yes, this is also a known issue. Unfortunately, the actual app names are not in the chart; so the way the PowerUp adds them is to look in the legend below and match based on color. After so many apps, the legend will just say "X more". These will unfortunately prevent PowerUps from looking up the name after about ~10 apps. As a workaround, you should break your heatmap into two.
![Screen Shot 2021-01-04 at 10 59 03 AM](https://user-images.githubusercontent.com/34926264/103559852-6f96d800-4e7c-11eb-8d1a-73a7786617b8.png)

**Comment by JACONDE** [comment]
I applied the workaround and it works. I need to split the headmaps in two charts
