### ISSUE TITLE
Gauge max rounding

### ISSUE THREAD

**Issue by bild675** [LucasHocker/DynatraceDashboardPowerups#25]
Gauge max appears to round down to 400 or up to 600, for a server with 512gb of memory, that's really a large difference. Is this just me, tried several values above and below 500. Can we get some better resolution on this?

**Comment by LucasHocker** [comment]
I've changed some logic with how the tick marks work. Can you please try again? and also paste the string you're using.

**Comment by bild675** [comment]
This looks much better, thanks

Memory !PU(gauge):stops=.5,.75,.9;colors=green,yellow,red;min=0;max=800
Update dashboard tile<javascript:;>Pin as new tile<javascript:;>


[cid:image001.png@01D70C3A.1432F7C0]

**Comment by LucasHocker** [comment]
Great! I'm glad it works for you. I'll go ahead and close the issue.

FYI, I also updated the example in the help. You should have 1 more color than stops. Currently your example will be:
- green: 0 - 50%
- yellow: 50-75%
- red: 75-90%
- also red: 90+%
