### ISSUE TITLE
Sankey Enhancement Request

### ISSUE THREAD

**Issue by TechShady** [LucasHocker/DynatraceDashboardPowerups#27]
Create a cleanup rule for the first column to remove nulls. I can change the underlying USQL to use Conversion Goals instead of User Actions, but this introduces nulls for actions that don't have a Conversion Goal.

[["Milestone - Pricing"],[],[],[],[],[],[],["Conversion - Trial"]] would become [["Milestone - Pricing"],["Conversion - Trial"]]

Thank you, sir...

**Comment by TechShady** [comment]
Modify the useraction or conversion string to add a "Start" in the beginning and an "End" at the end. This will make the Sankey chart more readable.

**Comment by LucasHocker** [comment]
Added `convHack=true` and `convHack=2` modes.
