### ISSUE TITLE
Feature Request / Enhancement - Colorize Behavior with no results found

### ISSUE THREAD

**Issue by jenrsparks** [LucasHocker/DynatraceDashboardPowerups#33]
We're making awesome use of the Colorize functionality to show how many instances of our application are running ('Process count per process group' metric), however when no instances are running, we get a "No data" result and by extension, the colorization does not work.

Is it possible to add an additional behavior for when no results are returned? In my case I would like to see red here, however I can imagine other scenarios where no results are a **good** thing.

**Comment by LucasHocker** [comment]
Yep that one makes sense. I've added this now. You can specify `nan=orange` and a CSS color. I've pushed the change to Github, so you can see it live by clicking the Gem icon and changing Library Location to Github. It'll be included in the next Chromestore version.
<img width="894" alt="Screen Shot 2021-04-17 at 1 59 57 PM" src="https://user-images.githubusercontent.com/34926264/115124024-9ee1d880-9f85-11eb-815d-6f799fc8c8a5.png">

**Comment by jenrsparks** [comment]
Big thank you! This is going to be a big quality of life bump for my L1 engineers.:D
