### ISSUE TITLE
Funnel powerup not working

### ISSUE THREAD

**Issue by sweber35** [LucasHocker/DynatraceDashboardPowerups#34]
Given the following funnel chart, Powerups extension is failing to manipulate the dashboard tile at all, despite other Powerups on the same dashboard working fine:
![image](https://user-images.githubusercontent.com/38842340/110162772-2d770d80-7dbd-11eb-97ef-664e0ef6fc98.png)
![image](https://user-images.githubusercontent.com/38842340/110162923-5d261580-7dbd-11eb-8e23-5b60fa2eefb5.png)

It appears to be related to this error:
```
POWERUP: Loading libs from: chrome-extension://dmpgdhbpdodhddciokonbahhbpaalmco/clientside.min.js...
Powerup: powerups complete.
POWERUP: ERROR  TypeError: Cannot read property '1' of undefined
POWERUP: Content script received: start_beacon
POWERUP: Content script received: crash_beacon
POWERUP: Content script received: end_beacon
```

**Comment by LucasHocker** [comment]
Found a bug where if required parameter `links` is not included, it would ERROR out. I've added graceful handling around it. Fix has been deployed to Github and will be included in next Chromestore version. You can see it now by clicking the Gem icon and changing Library Location to Github.
<img width="1490" alt="Screen Shot 2021-04-17 at 12 32 38 PM" src="https://user-images.githubusercontent.com/34926264/115121568-06ddf200-9f79-11eb-8f78-f7e0e334250e.png">
<img width="591" alt="Screen Shot 2021-04-17 at 12 26 41 PM" src="https://user-images.githubusercontent.com/34926264/115121572-0b0a0f80-9f79-11eb-9c9b-50d0f19fe47e.png">
