### ISSUE TITLE
Issue with Maths Power Up

### ISSUE THREAD

**Issue by Luke-Skelton** [LucasHocker/DynatraceDashboardPowerups#35]
Hello all,

I'm struggling with the maths returning data on my dashboard using the
![image](https://user-images.githubusercontent.com/63708199/111140145-e8e83080-8579-11eb-9d9f-e26ec8103bc3.png)
 plugin. See imagine attached. 

I have counts as my single values and using mark up values where my calculation is. When I come out of edit the query is still there. Are you able to assist why the calculation isn't working?

Kind regards,

Luke Skelton
lukeskelton@hastingsdirect.com

**Comment by LucasHocker** [comment]
Synced with Luke offline. Issue was related to unit selection in-product.

Luke also asked for a way to display Math PU data as a currency. I've added this. Pushed to Github now, available if using GitHub library location. Will be included in the next Chromestore release.
