### ISSUE TITLE
Heatmap showing weird names and no preserves the order

### ISSUE THREAD

**Issue by jmanuelip** [LucasHocker/DynatraceDashboardPowerups#38]
Hi.
I've seeing an unexpected behavior with heatmaps.  The problem is that from a list of the 10 worst APDEX by geographic location (builtin:apps.web.apdex.userType.geoBig),  it's showing locations that are not in the list, repeats some of the locations with different values and does not keep the order. I attach a screenshot showing a top on the left with the expected locations and values and what we get with the heatmap on the right.

![heatmap_issue](https://user-images.githubusercontent.com/55122563/113681384-2f850280-96c2-11eb-8464-a81fb510bbdd.PNG)

**Comment by LucasHocker** [comment]
Hmm... this is an interesting one. I don't think the heatmap is going to be the best visualization for your usecase. It's limited on the number series (~10), but the geo data is typically 400+ series. I made some enhancements to the heatmap to better show this limitation (see attached).

I think a better way of visualizing what you want here is to colorize the Toplist visual. This would give you glanceable view as to whether apdex is good or bad for specific geos.  The go-forward way to do this is with Explorer tiles which already support color thresholds. I tried it out but found that currently Explorer tiles do not support sorting, so it doesn't yet meet your usecase. I checked internally and the sorting should come in a few sprints (~ 1.220).

In the interim, I created a new powerup to colorize the Custom Chart toplist. See https://github.com/LucasHocker/DynatraceDashboardPowerups#topcolor. I think this will give you what you're looking for in the short term. The change is pushed to Github, so you can use it now by clicking the Gem icon and changing the Library Location to Github. It'll be included in the next Chromestore version. Please let me know if this works for your usecase.
<img width="1521" alt="Screen Shot 2021-04-17 at 9 55 14 AM" src="https://user-images.githubusercontent.com/34926264/115117981-c07f9780-9f66-11eb-8ec1-ef93e544b495.png">

**Comment by jmanuelip** [comment]
Hi, Lucas.

Thanks for it... it's so useful!

All the best
JMI

De: Lucas Hocker ***@***.***>
Enviado el: sábado, 17 de abril de 2021 17:23
Para: LucasHocker/DynatraceDashboardPowerups ***@***.***>
CC: Iglesias, Jose Manuel ***@***.***>; Author ***@***.***>
Asunto: Re: [LucasHocker/DynatraceDashboardPowerups] Heatmap showing weird names and no preserves the order (#38)


Hmm... this is an interesting one. I don't think the heatmap is going to be the best visualization for your usecase. It's limited on the number series (~10), but the geo data is typically 400+ series. I made some enhancements to the heatmap to better show this limitation (see attached).

I think a better way of visualizing what you want here is to colorize the Toplist visual. This would give you glanceable view as to whether apdex is good or bad for specific geos. The go-forward way to do this is with Explorer tiles which already support color thresholds. I tried it out but found that currently Explorer tiles do not support sorting, so it doesn't yet meet your usecase. I checked internally and the sorting should come in a few sprints (~ 1.220).

In the interim, I created a new powerup to colorize the Custom Chart toplist. See https://github.com/LucasHocker/DynatraceDashboardPowerups#topcolor<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLucasHocker%2FDynatraceDashboardPowerups%23topcolor&data=04%7C01%7Cjose.iglesias%40dynatrace.com%7C1b3f4472e08044bea63f08d901b4abc1%7C70ebe3a35b30435d9d677716d74ca190%7C1%7C1%7C637542697765459339%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NvX8LUv0%2Fw%2BZia1fuyxkkY33htvS2xrz6bPWCH7ZW%2FM%3D&reserved=0>. I think this will give you what you're looking for in the short term. The change is pushed to Github, so you can use it now by clicking the Gem icon and changing the Library Location to Github. It'll be included in the next Chromestore version. Please let me know if this works for your usecase.
[Screen Shot 2021-04-17 at 9 55 14 AM]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F34926264%2F115117981-c07f9780-9f66-11eb-8ec1-ef93e544b495.png&data=04%7C01%7Cjose.iglesias%40dynatrace.com%7C1b3f4472e08044bea63f08d901b4abc1%7C70ebe3a35b30435d9d677716d74ca190%7C1%7C1%7C637542697765469336%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8bpba%2FJT%2B9zkZoDdMLzuvxfFj%2BsHk4ODLgeaEJ%2BhU%2F4%3D&reserved=0>

-
