### ISSUE TITLE
Extension breaks when viewing publicly shared dashboard

### ISSUE THREAD

**Issue by edd-b** [LucasHocker/DynatraceDashboardPowerups#39]
Noticed that the extension breaks when viewing publicly shared dashboard with the 'monitoring opt-out' preference set to the default of unchecked. After checking this preference, the extension works as expected.

**Comment by LucasHocker** [comment]
Fix pushed to github. Will be included in next chromestore version. To try it out ahead of time click the Gem icon and change Library Location to Github.

Thanks for the detailed description! The bit about 'monitoring opt-out' put me on the right track straight away.
