### ISSUE TITLE
Colorize behavior for 'null' values or no results found

### ISSUE THREAD

**Issue by anilkjindal** [LucasHocker/DynatraceDashboardPowerups#40]
We are using colorize feature of the plugin for response times performance reporting.
The formula we are using to color code is following:
!PU(color):base=low;warn=16000;crit=18000

Currently, if no value is found in the specific time period dynatrace query returns 'null' result, which is marked red by the colorize function. Is there any way to mark null values in white or green as null represents just no values available in the time frame.
Please consider this as an enhancement request if this feature is not available. 

![image](https://user-images.githubusercontent.com/47995911/114965298-adf85600-9eb3-11eb-8aa6-490b753694ab.png)

**Comment by LucasHocker** [comment]
Done. It should show up gray now. Pushed to GitHub library location, will be included in next Chromestore update. To see the update prior, please click the Gem icon and set preference for Library Location to GitHub.
![Screen Shot 2021-04-16 at 7 12 48 PM](https://user-images.githubusercontent.com/34926264/115096896-da7c9400-9eec-11eb-8c0f-676f18178699.png)

**Comment by anilkjindal** [comment]
Thanks for considering this, it is a great help, we will test this and update after Chromestore update.
