### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND - cannot load the openkit js

### ISSUE THREAD

**Issue by ggivati** [LucasHocker/DynatraceDashboardPowerups#6]
In version 127, the openkit is not loaded,

![image](https://user-images.githubusercontent.com/18489043/99187515-be1ed480-275f-11eb-82a5-043bdc721ace.png)

**Comment by LucasHocker** [comment]
Seems the openkit.js was stripped out of the package for some reason. Here's a quick workaround:
1) Click the Powerup 💎 icon in your Chrome address bar
2) Expand Preferences, change Library Location to "GitHub (newer)"
3) Click Save
4) Refresh your dashboard
<img width="332" alt="Screen Shot 2020-11-15 at 8 49 27 AM" src="https://user-images.githubusercontent.com/34926264/99188104-d4a53b80-271f-11eb-81e9-702df85bbc9c.png">

**Comment by ggivati** [comment]
Thanks. the workaround did the job.

**Comment by LucasHocker** [comment]
Fix staged for 1.29. Awaiting Google ChromeStore to approve already submitted 1.28, and then will submit 1.29.

**Comment by LucasHocker** [comment]
Notice posted at top of README.md

**Comment by LucasHocker** [comment]
Confirmed fixed in 1.29, which has been released.
