### ISSUE TITLE
Uncaught ReferenceError: uuidv4 is not defined

### ISSUE THREAD

**Issue by KeaneYu** [LucasHocker/DynatraceDashboardPowerups#7]
Hi Lucas, 
Got below error in 1.28, and could not change to GITHUB (no effect after click save button).
![image](https://user-images.githubusercontent.com/14102746/99514065-49999f00-29c6-11eb-8752-bb6b636318b4.png)

**Comment by LucasHocker** [comment]
I see that Google just approved version 1.29. Can you please confirm that your copy updated and that it resolved the issues?

**Comment by KeaneYu** [comment]
Wow, just in time, 1.29 worke! Thank you!
